version: '3.2'

services:
    db:
        image: postgres:10
        ports:
            - "5432:5432"
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=dev
            - POSTGRES_USER=dev
            - POSTGRES_PASSWORD=dev
volumes:
    db:
